// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetInline, type SetInlineProps } from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_INLINE_CHILDREN = "__SET_SLOT_INLINE_CHILDREN__";

export type InlineProps = Omit<SetInlineProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Inline(props: InlineProps): ReturnType<typeof reactify> {
  const { as, align, children, gap, id, justify, nowrap, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetInline({
    as,
    align,
    children: hasChildren
      ? (SLOT_INLINE_CHILDREN as unknown as SetInlineProps["children"])
      : undefined,
    gap,
    id,
    justify,
    nowrap,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_INLINE_CHILDREN]: children } : {}),
    },
  );
}
