// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetShape, type SetShapeProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type ShapeProps = SetShapeProps & NativeAttrsFor<HTMLDivElement>;

export function Shape(props: ShapeProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetShape(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
