// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetPage, type SetPageProps } from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_PAGE_BANNER = "__SET_SLOT_PAGE_BANNER__";
const SLOT_PAGE_HEADER = "__SET_SLOT_PAGE_HEADER__";
const SLOT_PAGE_CHILDREN = "__SET_SLOT_PAGE_CHILDREN__";
const SLOT_PAGE_FOOTER = "__SET_SLOT_PAGE_FOOTER__";

export type PageProps = Omit<
  SetPageProps,
  "banner" | "header" | "children" | "footer"
> & {
  banner?: ReactNode;
  header: ReactNode;
  children?: ReactNode;
  footer: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Page(props: PageProps): ReturnType<typeof reactify> {
  const {
    banner,
    children,
    centerMain,
    header,
    headerBorder,
    headerSize,
    id,
    stickyHeader,
    footer,
    ...rest
  } = props;
  const hasBanner = banner != null && banner !== false;
  const hasChildren = children != null && children !== false;
  const node = buildSetPage({
    banner: hasBanner
      ? (SLOT_PAGE_BANNER as unknown as SetPageProps["banner"])
      : undefined,
    children: hasChildren
      ? (SLOT_PAGE_CHILDREN as unknown as SetPageProps["children"])
      : undefined,
    centerMain,
    header: SLOT_PAGE_HEADER as unknown as SetPageProps["header"],
    headerBorder,
    headerSize,
    id,
    stickyHeader,
    footer: SLOT_PAGE_FOOTER as unknown as SetPageProps["footer"],
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasBanner ? { [SLOT_PAGE_BANNER]: banner } : {}),
      [SLOT_PAGE_HEADER]: header,
      ...(hasChildren ? { [SLOT_PAGE_CHILDREN]: children } : {}),
      [SLOT_PAGE_FOOTER]: footer,
    },
  );
}
