// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetLink, type SetLinkProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_LINK_ICON = "__SET_SLOT_LINK_ICON__";

export type LinkProps = Omit<SetLinkProps, "icon"> & {
  icon?: ReactNode;
} & NativeAttrsFor<HTMLAnchorElement>;

export function Link(props: LinkProps): ReturnType<typeof reactify> {
  const {
    appearance,
    current,
    download,
    href,
    id,
    icon,
    iconPlacement,
    label,
    labelVisibility,
    rel,
    size,
    target,
    tone,
    underline,
    ...rest
  } = props;
  const hasIcon = icon != null && icon !== false;
  const node = buildSetLink({
    appearance,
    current,
    download,
    href,
    id,
    icon: hasIcon
      ? (SLOT_LINK_ICON as unknown as SetLinkProps["icon"])
      : undefined,
    iconPlacement,
    label,
    labelVisibility,
    rel,
    size,
    target,
    tone,
    underline,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasIcon ? { [SLOT_LINK_ICON]: icon } : {}),
    },
  );
}
