// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetDivider, type SetDividerProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type DividerProps = SetDividerProps & NativeAttrsFor<HTMLElement>;

export function Divider(props: DividerProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetDivider(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
