// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetProse, type SetProseProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_PROSE_CHILDREN = "__SET_SLOT_PROSE_CHILDREN__";

export type ProseProps = Omit<SetProseProps, "children"> & {
  children: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Prose(props: ProseProps): ReturnType<typeof reactify> {
  const {
    children,
    align,
    hangingPunctuation,
    id,
    measured,
    responsive,
    ...rest
  } = props;
  const node = buildSetProse({
    children: SLOT_PROSE_CHILDREN as unknown as SetProseProps["children"],
    align,
    hangingPunctuation,
    id,
    measured,
    responsive,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_PROSE_CHILDREN]: children,
    },
  );
}
