// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetDetails, type SetDetailsProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_DETAILS_CHILDREN = "__SET_SLOT_DETAILS_CHILDREN__";

export type DetailsProps = Omit<SetDetailsProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDetailsElement>;

export function Details(props: DetailsProps): ReturnType<typeof reactify> {
  const { children, id, inlineSize, open, summary, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetDetails({
    children: hasChildren
      ? (SLOT_DETAILS_CHILDREN as unknown as SetDetailsProps["children"])
      : undefined,
    id,
    inlineSize,
    open,
    summary,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_DETAILS_CHILDREN]: children } : {}),
    },
  );
}
