// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetSurface, type SetSurfaceProps } from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_SURFACE_CHILDREN = "__SET_SLOT_SURFACE_CHILDREN__";

export type SurfaceProps = Omit<SetSurfaceProps, "children"> & {
  children: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Surface(props: SurfaceProps): ReturnType<typeof reactify> {
  const { children, contentTheme, id, variant, ...rest } = props;
  const node = buildSetSurface({
    children: SLOT_SURFACE_CHILDREN as unknown as SetSurfaceProps["children"],
    contentTheme,
    id,
    variant,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_SURFACE_CHILDREN]: children,
    },
  );
}
