// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetSpinner, type SetSpinnerProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type SpinnerProps = SetSpinnerProps & NativeAttrsFor<HTMLSpanElement>;

export function Spinner(props: SpinnerProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetSpinner(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
