// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetFigure, type SetFigureProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_FIGURE_CHILDREN = "__SET_SLOT_FIGURE_CHILDREN__";
const SLOT_FIGURE_CAPTION = "__SET_SLOT_FIGURE_CAPTION__";

export type FigureProps = Omit<SetFigureProps, "children" | "caption"> & {
  children: ReactNode;
  caption: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Figure(props: FigureProps): ReturnType<typeof reactify> {
  const { align, caption, children, id, responsive, ...rest } = props;
  const node = buildSetFigure({
    align,
    caption: SLOT_FIGURE_CAPTION as unknown as SetFigureProps["caption"],
    children: SLOT_FIGURE_CHILDREN as unknown as SetFigureProps["children"],
    id,
    responsive,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_FIGURE_CHILDREN]: children,
      [SLOT_FIGURE_CAPTION]: caption,
    },
  );
}
