// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetSwitch, type SetSwitchProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type SwitchProps = SetSwitchProps & NativeAttrsFor<HTMLDivElement>;

export function Switch(props: SwitchProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetSwitch(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
