// Generated by scripts/generate-icons.mjs — do not edit directly.
// The shipped icons: the TDesign names in icons-tdesign.ts plus the first-party
// icons in icons-custom.ts.
// Regenerate with `pnpm icons:generate`.

export interface IconNode {
  tag: string;
  attrs: Record<string, string>;
  children?: IconNode[];
}

export const ICON_NODES: Record<string, IconNode[]> = {
  adjustment: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M21 5L10 5M10 5C10 6.10457 9.10457 7 8 7C6.89543 7 6 6.10457 6 5M10 5C10 3.89543 9.10457 3 8 3C6.89543 3 6 3.89543 6 5M6 5L3 5M21 19H10M10 19C10 20.1046 9.10457 21 8 21C6.89543 21 6 20.1046 6 19M10 19C10 17.8954 9.10457 17 8 17C6.89543 17 6 17.8954 6 19M3 12H14M14 12C14 13.1046 14.8954 14 16 14C17.1046 14 18 13.1046 18 12M14 12C14 10.8954 14.8954 10 16 10C17.1046 10 18 10.8954 18 12M6 19H3M18 12H21",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "arrow-down": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M17.5 13.6L12 19.1L6.5 13.6M12 17.85V4.85",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "arrow-left": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M11 6.5L5.5 12L11 17.5M6.75 12H19.75",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "arrow-left-right-1": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M15.5 4L19 7.5L15.5 11M17.75 7.5H5.5M8.5 20L5 16.5L8.5 13M6.25 16.5H18.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "arrow-right": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M13 17.5L18.5 12L13 6.5M17.25 12L4.25 12",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "arrow-up": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M17.5 10.5L12 5L6.5 10.5M12 6.25V19.25",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "arrow-up-down-1": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M7.5 6.25V18.5M13 15.5L16.5 19L20 15.5M16.5 17.75V5.50001M11 8.5L7.5 5L4 8.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "check-circle": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M16.5 9L10.5 15L7.5 12",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "chevron-down": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M17.5 9.5L12 15L6.5 9.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "chevron-right": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M9.5 17.5L15 12L9.5 6.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  circle: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "circle",
          attrs: {
            cx: "12",
            cy: "12",
            r: "10",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "city-6": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M12 21V16M7 21H2V9H7V21ZM22 7V21H17V7H22Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M17 3H7V21H17V3Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  close: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M16.9503 7.05029L12.0005 12M12.0005 12L7.05078 16.9498M12.0005 12L16.9503 16.9498M12.0005 12L7.05078 7.05029",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  copy: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M10 10H21V21H10V10Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M14 6.5V3L3 3L3 14H6.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  download: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M16.5 10.5L12 15L7.5 10.5M12 13.75V4",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M20.5 15V20H3.5V15",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  enter: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M5.75 16H16C17.6569 16 19 14.6569 19 13L19 5M8 12.5L4.5 16L8 19.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "error-circle": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M12 7.5V13M12 16.5H12.0039V16.5039H12V16.5Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "error-triangle": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M12.0003 3L22.2194 20.7H1.78125L12.0003 3Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M12 10.5V14M12 17.5H12.0039V17.5039H12V17.5Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  horizontal: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "g",
          attrs: {},
          children: [
            {
              tag: "path",
              attrs: {
                d: "M3 11H21V21H3V11Z",
              },
            },
            {
              tag: "path",
              attrs: {
                d: "M3 3H21V7H3V3Z",
              },
            },
          ],
        },
      ],
    },
  ],
  "info-circle": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M12 16.5L12 11M12 7.5L11.9961 7.5L11.9961 7.49609L12 7.49609L12 7.5Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  jump: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M9 4L4 4L4 20L20 20L20 15",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M19.25 4.75L12 12M14 4H20L20 10",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  layers: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M4.5 6.125L12 3L19.5 6.125L12 9.25L4.5 6.125Z",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M3 11.5005L12 15.3771L21 11.5005M21 17.5005L12 21.3771L3 17.5005",
          },
        },
      ],
    },
  ],
  link: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M11.6762 6.99023L13.9998 4.6666C15.4726 3.19382 17.8604 3.19382 19.3332 4.6666C20.806 6.13938 20.806 8.52723 19.3332 10L17.0096 12.3236M6.98974 11.6766L4.66611 14.0003C3.19333 15.4731 3.19333 17.8609 4.66611 19.3337C6.13889 20.8065 8.52675 20.8065 9.99953 19.3337L12.3232 17.0101M13.9985 9.99989L9.99847 14",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  member: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M16 20V19C16 16.7909 14.2091 15 12 15H5C2.79086 15 1 16.7909 1 19V20M12.5 7C12.5 9.20914 10.7091 11 8.5 11C6.29086 11 4.5 9.20914 4.5 7C4.5 4.79086 6.29086 3 8.5 3C10.7091 3 12.5 4.79086 12.5 7Z",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M15.5 11C17.7091 11 19.5 9.20914 19.5 7C19.5 4.79086 17.7091 3 15.5 3M23 20V19C23 16.7909 21.2091 15 19 15",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "panel-left": [
    {
      tag: "path",
      attrs: {
        d: "M3 3H21V21H3V3Z",
        "stroke-linecap": "square",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M9 3V21",
        "stroke-linecap": "square",
      },
    },
  ],
  pantone: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3.35389 10.3333L20.8245 10.3333L19.0009 5L3.35389 10.3333ZM3.35389 10.3333L17.1433 5.63318L14.1465 1.43164L2.99942 10.3359M3.35389 10.3333L2.99942 10.3359M2.99942 10.3359H2.5",
          },
        },
        {
          tag: "g",
          attrs: {},
          children: [
            {
              tag: "path",
              attrs: {
                d: "M6.28516 15.1641H6.28906V15.168H6.28516V15.1641Z",
                "stroke-linecap": "square",
              },
            },
            {
              tag: "path",
              attrs: {
                d: "M22 10.333V19.9997L2 19.9997L2 10.333L22 10.333Z",
                "stroke-linecap": "square",
              },
            },
          ],
        },
      ],
    },
  ],
  play: [
    {
      tag: "path",
      attrs: {
        fill: "currentColor",
        d: "M18.25 11.9998L8.5 17.6289L8.5 6.37061L18.25 11.9998Z",
      },
    },
  ],
  rectangle: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 3H21V21H3z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  refresh: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M21.448 13C20.9483 17.7767 16.909 21.5 12 21.5C8.18227 21.5 4.89052 19.248 3.38065 16M2.5 20.5V15.5H5.5M2.55176 11C3.05145 6.22334 7.09079 2.5 11.9998 2.5C15.8175 2.5 19.1092 4.75197 20.6191 8M21.4998 3.5V8.5H18.4998",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "robot-1": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M19.5 21V19.5C19.5 17.2909 17.7091 15.5 15.5 15.5H8.5C6.29086 15.5 4.5 17.2909 4.5 19.5V21M12 4V2M10 12H14C16.2091 12 18 10.2091 18 8C18 5.79086 16.2091 4 14 4H10C7.79086 4 6 5.79086 6 8C6 10.2091 7.79086 12 10 12ZM10.25 8C10.25 8.13807 10.1381 8.25 10 8.25C9.86193 8.25 9.75 8.13807 9.75 8C9.75 7.86193 9.86193 7.75 10 7.75C10.1381 7.75 10.25 7.86193 10.25 8ZM14 8.25C13.8619 8.25 13.75 8.13807 13.75 8C13.75 7.86193 13.8619 7.75 14 7.75C14.1381 7.75 14.25 7.86193 14.25 8C14.25 8.13807 14.1381 8.25 14 8.25Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  search: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M15.8027 15.8037L21.106 21.107",
            "stroke-linecap": "square",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M15.8033 15.8033C12.8744 18.7322 8.12563 18.7322 5.1967 15.8033C2.26777 12.8744 2.26777 8.12563 5.1967 5.1967C8.12563 2.26777 12.8744 2.26777 15.8033 5.1967C18.7322 8.12563 18.7322 12.8744 15.8033 15.8033Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "setting-1": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M9.40811 4.95996L10.0001 2H14.0001L14.5921 4.95996C15.4027 5.25851 16.1475 5.69306 16.7989 6.23595L19.6604 5.26796L21.6604 8.73206L19.3922 10.7254C19.4632 11.1396 19.5001 11.5655 19.5001 12C19.5001 12.4345 19.4632 12.8604 19.3922 13.2747L21.6604 15.268L19.6604 18.7321L16.7989 17.7641C16.1475 18.3069 15.4027 18.7415 14.5921 19.04L14.0001 22H10.0001L9.40811 19.04C8.5975 18.7415 7.85268 18.3069 7.20131 17.7641L4.33984 18.7321L2.33984 15.268L4.60798 13.2747C4.53705 12.8604 4.5001 12.4345 4.5001 12C4.5001 11.5655 4.53705 11.1396 4.60797 10.7254L2.33984 8.73206L4.33984 5.26796L7.20129 6.23595C7.85266 5.69306 8.59749 5.25851 9.40811 4.95996Z",
            "fill-rule": "evenodd",
            "stroke-linecap": "square",
            "clip-rule": "evenodd",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M16 12C16 14.2091 14.2091 16 12 16C9.79086 16 8 14.2091 8 12C8 9.79086 9.79086 8 12 8C14.2091 8 16 9.79086 16 12Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  swap: [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M21 14.5H4L9 19.5M3 9.5L20 9.5L15 4.5",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "user-1": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M19.5 20V19C19.5 16.7909 17.7091 15 15.5 15H8.5C6.29086 15 4.5 16.7909 4.5 19V20M16 7C16 9.20914 14.2091 11 12 11C9.79086 11 8 9.20914 8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
  "view-list": [
    {
      tag: "g",
      attrs: {},
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 5H21M3 12H21M3 19H21",
            "stroke-linecap": "square",
          },
        },
      ],
    },
  ],
};
