// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetRadios, type SetRadiosProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type RadiosProps = SetRadiosProps & NativeAttrsFor<HTMLFieldSetElement>;

export function Radios(props: RadiosProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetRadios(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
