// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetHeading, type SetHeadingProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type HeadingProps = SetHeadingProps & NativeAttrsFor<HTMLElement>;

export function Heading(props: HeadingProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetHeading(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
