// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetHeading, type SetHeadingProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_HEADING_CHILDREN = "__SET_SLOT_HEADING_CHILDREN__";

export type HeadingProps = Omit<SetHeadingProps, "children"> & {
  children: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Heading(props: HeadingProps): ReturnType<typeof reactify> {
  const {
    align,
    children,
    id,
    level,
    linkVisited,
    opticalAlign,
    responsive,
    size,
    ...rest
  } = props;
  const node = buildSetHeading({
    align,
    children: SLOT_HEADING_CHILDREN as unknown as SetHeadingProps["children"],
    id,
    level,
    linkVisited,
    opticalAlign,
    responsive,
    size,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_HEADING_CHILDREN]: children,
    },
  );
}
