// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetRoot, type SetRootProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_ROOT_CHILDREN = "__SET_SLOT_ROOT_CHILDREN__";

export type RootProps = Omit<SetRootProps, "children"> & {
  children: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Root(props: RootProps): ReturnType<typeof reactify> {
  const {
    appOverscrollBehavior,
    appRoot,
    brand,
    children,
    dir,
    id,
    lang,
    theme,
    ...rest
  } = props;
  const node = buildSetRoot({
    appOverscrollBehavior,
    appRoot,
    brand,
    children: SLOT_ROOT_CHILDREN as unknown as SetRootProps["children"],
    dir,
    id,
    lang,
    theme,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_ROOT_CHILDREN]: children,
    },
  );
}
