// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetPanel, type SetPanelProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_PANEL_CHILDREN = "__SET_SLOT_PANEL_CHILDREN__";

export type PanelProps = Omit<SetPanelProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Panel(props: PanelProps): ReturnType<typeof reactify> {
  const { children, id, padding, surface, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetPanel({
    children: hasChildren
      ? (SLOT_PANEL_CHILDREN as unknown as SetPanelProps["children"])
      : undefined,
    id,
    padding,
    surface,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_PANEL_CHILDREN]: children } : {}),
    },
  );
}
