// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetCard, type SetCardProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_CARD_DESCRIPTION = "__SET_SLOT_CARD_DESCRIPTION__";
const SLOT_CARD_NOTE = "__SET_SLOT_CARD_NOTE__";

export type CardProps = Omit<SetCardProps, "description" | "note"> & {
  description: ReactNode;
  note?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Card(props: CardProps): ReturnType<typeof reactify> {
  const { description, headingLevel, href, id, note, surface, title, ...rest } =
    props;
  const hasNote = note != null && note !== false;
  const node = buildSetCard({
    description:
      SLOT_CARD_DESCRIPTION as unknown as SetCardProps["description"],
    headingLevel,
    href,
    id,
    note: hasNote
      ? (SLOT_CARD_NOTE as unknown as SetCardProps["note"])
      : undefined,
    surface,
    title,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_CARD_DESCRIPTION]: description,
      ...(hasNote ? { [SLOT_CARD_NOTE]: note } : {}),
    },
  );
}
