// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetLightswitch,
  defineSetLightswitch,
  SET_LIGHTSWITCH_EVENT_CHANGE,
  type SetLightswitchProps,
} from "@monospaced/set-core";
import {
  type Ref,
  type RefCallback,
  useCallback,
  useEffect,
  useRef,
} from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

function assignRef<T>(ref: Ref<T> | undefined, value: T | null): void {
  if (typeof ref === "function") ref(value);
  else if (ref) (ref as { current: T | null }).current = value;
}

export type LightswitchChangeHandler = (event: Event) => void;

export type LightswitchProps = SetLightswitchProps &
  NativeAttrsFor<HTMLElement> & {
    onChange?: LightswitchChangeHandler;
  };

export function Lightswitch(
  props: LightswitchProps,
): ReturnType<typeof reactify> {
  const { onChange, ref: callerRef, ...rest } = props;
  useEffect(() => {
    defineSetLightswitch();
  }, []);
  const elRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    const el = elRef.current;
    if (!el || !onChange) return;
    el.addEventListener(
      SET_LIGHTSWITCH_EVENT_CHANGE,
      onChange as EventListener,
    );
    return () =>
      el.removeEventListener(
        SET_LIGHTSWITCH_EVENT_CHANGE,
        onChange as EventListener,
      );
  }, [onChange]);
  const mergedRef = useCallback<RefCallback<HTMLElement>>(
    (node) => {
      elRef.current = node;
      assignRef(callerRef, node);
    },
    [callerRef],
  );
  return reactify(buildSetLightswitch(props), {
    ...pickNativeExtras(rest as unknown as Record<string, unknown>),
    ref: mergedRef,
  });
}
