// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetStack, type SetStackProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_STACK_CHILDREN = "__SET_SLOT_STACK_CHILDREN__";

export type StackProps = Omit<SetStackProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Stack(props: StackProps): ReturnType<typeof reactify> {
  const { align, as, children, gap, id, responsive, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetStack({
    align,
    as,
    children: hasChildren
      ? (SLOT_STACK_CHILDREN as unknown as SetStackProps["children"])
      : undefined,
    gap,
    id,
    responsive,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_STACK_CHILDREN]: children } : {}),
    },
  );
}
