// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetGrid, type SetGridProps } from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_GRID_CHILDREN = "__SET_SLOT_GRID_CHILDREN__";

export type GridProps = Omit<SetGridProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Grid(props: GridProps): ReturnType<typeof reactify> {
  const { children, gap, id, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetGrid({
    children: hasChildren
      ? (SLOT_GRID_CHILDREN as unknown as SetGridProps["children"])
      : undefined,
    gap,
    id,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_GRID_CHILDREN]: children } : {}),
    },
  );
}
