// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetLogo, type SetLogoProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type LogoProps = SetLogoProps & NativeAttrsFor<HTMLDivElement>;

export function Logo(props: LogoProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetLogo(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
