// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetFieldset, type SetFieldsetProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_FIELDSET_CHILDREN = "__SET_SLOT_FIELDSET_CHILDREN__";

export type FieldsetProps = Omit<SetFieldsetProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLFieldSetElement>;

export function Fieldset(props: FieldsetProps): ReturnType<typeof reactify> {
  const {
    children,
    description,
    disabled,
    id,
    invalid,
    legend,
    inlineSize,
    ...rest
  } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetFieldset({
    children: hasChildren
      ? (SLOT_FIELDSET_CHILDREN as unknown as SetFieldsetProps["children"])
      : undefined,
    description,
    disabled,
    id,
    invalid,
    legend,
    inlineSize,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_FIELDSET_CHILDREN]: children } : {}),
    },
  );
}
