// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetNav,
  type SetNavProps,
  defineSetNav,
} from "@measured/set-core";
import { useEffect } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type NavProps = SetNavProps & NativeAttrsFor<HTMLElement>;

export function Nav(props: NavProps): ReturnType<typeof reactify> {
  useEffect(() => {
    defineSetNav();
  }, []);
  return reactify(
    buildSetNav(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
