// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetInput, type SetInputProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type InputProps = SetInputProps & NativeAttrsFor<HTMLDivElement>;

export function Input(props: InputProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetInput(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
