// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetContainer,
  type SetContainerProps,
} from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_CONTAINER_CHILDREN = "__SET_SLOT_CONTAINER_CHILDREN__";

export type ContainerProps = Omit<SetContainerProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Container(props: ContainerProps): ReturnType<typeof reactify> {
  const { children, gutter, id, maxInlineSize, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetContainer({
    children: hasChildren
      ? (SLOT_CONTAINER_CHILDREN as unknown as SetContainerProps["children"])
      : undefined,
    gutter,
    id,
    maxInlineSize,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_CONTAINER_CHILDREN]: children } : {}),
    },
  );
}
