// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetCheckbox, type SetCheckboxProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type CheckboxProps = SetCheckboxProps & NativeAttrsFor<HTMLDivElement>;

export function Checkbox(props: CheckboxProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetCheckbox(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
