// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetAvatar, type SetAvatarProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type AvatarProps = SetAvatarProps & NativeAttrsFor<HTMLSpanElement>;

export function Avatar(props: AvatarProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetAvatar(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
