import type { SetComponentSpec } from "@monospaced/set-core";

import { classify, pascalCase, screamingSnake } from "../shared/spec.ts";

// -----------------------------------------------------------------------------
// Reactify import contract.
//
// The emitter wires every generated wrapper to these exports of
// `packages/react/src/reactify.tsx`. If any of these move or rename there,
// update here — generation will still succeed but the emitted wrappers
// would fail to compile against the runtime module, making this the one
// place to keep the coupling explicit.
// -----------------------------------------------------------------------------

const REACTIFY_IMPORT_PATH = "../../reactify";
const REACTIFY_VALUE_IMPORTS = ["pickNativeExtras", "reactify"] as const;
const REACTIFY_TYPE_IMPORTS = ["NativeAttrsFor"] as const;

/**
 * Header comment prepended to every emitted file. Intentionally plain
 * prose — the `@generated` tag is avoided because GitHub collapses those
 * diffs in PR review by default, and we want reviewers to see changes to
 * the emitted output (they're a useful signal when the emitter or a SPEC
 * changes).
 */
const GENERATED_HEADER = [
  "// Generated by @monospaced/set-adapter — do not edit directly.",
  "// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).",
  "",
].join("\n");

// -----------------------------------------------------------------------------
// Emit pipeline.
//
// Every wrapper is composed from a small number of orthogonal concerns:
//   - content archetype (pass-through or slotted)
//   - custom-element registration (defineSet* useEffect)
//   - custom-event wiring (onEvent props, addEventListener useEffects, ref
//     merge)
//
// Each concern contributes to an `EmitParts` record; a single renderer joins
// them into a prettier-ready TSX source string.
// -----------------------------------------------------------------------------

interface EmitParts {
  coreValueImports: Set<string>;
  coreTypeImports: Set<string>;
  reactValueImports: Set<string>;
  reactTypeImports: Set<string>;
  constants: string[];
  helpers: string[];
  exportedTypes: string[];
  /** Extra lines added inside the `Props` type body. */
  propsTypeLines: string[];
  /** Lines added inside the function body, in order. */
  functionBody: string[];
  /** Full signature, e.g. `export function Banner(props: BannerProps): ... {`. */
  functionSignature: string;
  /** Final return expression for the function. */
  returnExpr: string;
  /**
   * Index into `functionBody` of the leading `const { … } = props;`
   * destructure line, if a content contributor emitted one. Lets the
   * events contributor find it without pattern-matching.
   */
  destructureIndex: number | null;
}

function newParts(): EmitParts {
  return {
    coreValueImports: new Set(),
    coreTypeImports: new Set(),
    reactValueImports: new Set(),
    reactTypeImports: new Set(),
    constants: [],
    helpers: [],
    exportedTypes: [],
    propsTypeLines: [],
    functionBody: [],
    functionSignature: "",
    returnExpr: "",
    destructureIndex: null,
  };
}

function renderParts(parts: EmitParts): string {
  const externalImports: string[] = [];
  const relativeImports: string[] = [];

  externalImports.push(
    renderImport(
      "@monospaced/set-core",
      [...parts.coreValueImports],
      [...parts.coreTypeImports],
    ),
  );

  const reactValues = [...parts.reactValueImports];
  const reactTypes = [...parts.reactTypeImports];
  if (reactValues.length > 0 || reactTypes.length > 0) {
    externalImports.push(renderImport("react", reactValues, reactTypes));
  }

  relativeImports.push(
    renderImport(
      REACTIFY_IMPORT_PATH,
      REACTIFY_VALUE_IMPORTS,
      REACTIFY_TYPE_IMPORTS,
    ),
  );

  const importBlock = [
    externalImports.join("\n"),
    relativeImports.join("\n"),
  ].join("\n\n");

  const sections: string[] = [importBlock];
  if (parts.constants.length > 0) sections.push(parts.constants.join("\n"));
  if (parts.helpers.length > 0) sections.push(parts.helpers.join("\n\n"));
  if (parts.exportedTypes.length > 0) {
    sections.push(parts.exportedTypes.join("\n\n"));
  }

  sections.push(
    `${parts.functionSignature} {\n${parts.functionBody.join("\n")}\n  return ${parts.returnExpr};\n}`,
  );

  return GENERATED_HEADER + sections.join("\n\n") + "\n";
}

/**
 * Render a single import statement. If the import has only types and no
 * values, use the `import type { ... }` form so prettier + eslint stay
 * happy. Otherwise interleave values and types alphabetically with inline
 * `type` prefixes so the emitted order matches hand-authored convention.
 */
function renderImport(
  source: string,
  values: ReadonlyArray<string>,
  types: ReadonlyArray<string>,
): string {
  if (values.length === 0) {
    const sorted = [...types].sort();
    return `import type {\n${sorted.map((t) => `  ${t},`).join("\n")}\n} from "${source}";`;
  }
  const items = [
    ...values.map((v) => ({ key: v, text: v })),
    ...types.map((t) => ({ key: t, text: `type ${t}` })),
  ].sort((a, b) => a.key.localeCompare(b.key));
  return `import {\n${items.map((i) => `  ${i.text},`).join("\n")}\n} from "${source}";`;
}

// -----------------------------------------------------------------------------
// Top-level entry.
// -----------------------------------------------------------------------------

export function emitWrapperSource(spec: SetComponentSpec): string {
  const parts = newParts();
  contributeContent(parts, spec);
  if (isCustomElement(spec)) contributeCustomElement(parts, spec);
  if (hasEvents(spec)) contributeEvents(parts, spec);
  return renderParts(parts);
}

/**
 * Emit the barrel `packages/react/src/index.ts` that re-exports every
 * generated wrapper plus its derived types.
 */
export function emitIndexSource(
  specs: ReadonlyArray<SetComponentSpec>,
): string {
  const sorted = [...specs].sort((a, b) => a.name.localeCompare(b.name));
  const blocks: string[] = [];
  for (const spec of sorted) {
    const pascal = pascalCase(spec.name);
    const names: string[] = [pascal];
    const events = Object.entries(spec.events);
    for (const [eventName, eventSpec] of events) {
      const action = stripSetPrefix(eventName, spec.name);
      const baseName = `${pascal}${pascalCase(action)}`;
      if (eventSpec.detail) {
        names.push(`type ${baseName}Detail`);
        names.push(`type ${baseName}Event`);
      }
      names.push(`type ${baseName}Handler`);
    }
    names.push(`type ${pascal}Props`);
    names.sort((a, b) =>
      a.replace(/^type /, "").localeCompare(b.replace(/^type /, "")),
    );
    blocks.push(
      `export {\n${names.map((n) => `  ${n},`).join("\n")}\n} from "./components/${spec.name}/${spec.name}";`,
    );
  }
  blocks.push(
    `export { defineSetComponents as defineSetAll } from "@monospaced/set-core";`,
  );
  return GENERATED_HEADER + blocks.join("\n") + "\n";
}

function isCustomElement(spec: SetComponentSpec): boolean {
  const element = spec.output.element;
  if (typeof element !== "string") return false;
  return element.startsWith("set-");
}

function hasEvents(spec: SetComponentSpec): boolean {
  return Object.keys(spec.events).length > 0;
}

/**
 * HTML tag → DOM interface used in emitted `NativeAttrsFor<T>` type
 * expressions. Hand-curated: covers every tag currently referenced in
 * core's `output.element` strings plus a few structural tags that map
 * to `HTMLElement` explicitly. Generation throws on any unmapped tag so
 * gaps surface at build time rather than silently losing ref/event
 * typing precision.
 */
const ELEMENT_INTERFACE: Record<string, string> = {
  a: "HTMLAnchorElement",
  article: "HTMLElement",
  aside: "HTMLElement",
  button: "HTMLButtonElement",
  details: "HTMLDetailsElement",
  div: "HTMLDivElement",
  fieldset: "HTMLFieldSetElement",
  figure: "HTMLElement",
  footer: "HTMLElement",
  h1: "HTMLHeadingElement",
  h2: "HTMLHeadingElement",
  h3: "HTMLHeadingElement",
  h4: "HTMLHeadingElement",
  h5: "HTMLHeadingElement",
  h6: "HTMLHeadingElement",
  header: "HTMLElement",
  hr: "HTMLHRElement",
  input: "HTMLInputElement",
  label: "HTMLLabelElement",
  li: "HTMLLIElement",
  main: "HTMLElement",
  nav: "HTMLElement",
  ol: "HTMLOListElement",
  p: "HTMLParagraphElement",
  section: "HTMLElement",
  span: "HTMLSpanElement",
  svg: "SVGSVGElement",
  textarea: "HTMLTextAreaElement",
  ul: "HTMLUListElement",
};

/**
 * DOM interface to use for this SPEC's host. Polymorphic (`switch`) hosts
 * and `set-*` custom elements both resolve to `HTMLElement`. Plain HTML
 * tags are looked up in `ELEMENT_INTERFACE`; an unmapped tag throws so
 * the gap surfaces at generation time.
 */
function hostInterface(spec: SetComponentSpec): string {
  const element = spec.output.element;
  if (typeof element !== "string") return "HTMLElement";
  if (element.startsWith("set-")) return "HTMLElement";
  const iface = ELEMENT_INTERFACE[element];
  if (!iface) {
    throw new Error(
      `hostInterface: "${element}" (used by SPEC "${spec.name}") has no entry in ELEMENT_INTERFACE. Add one to packages/adapter/src/react/emit.ts so the wrapper gets precise DOM typing.`,
    );
  }
  return iface;
}

// -----------------------------------------------------------------------------
// Content contributors.
//
// Either pass-through (scalar props only, no slot substitution) or slotted
// (one or more html slots substituted via sentinels; text slots stay scalar).
// -----------------------------------------------------------------------------

function contributeContent(parts: EmitParts, spec: SetComponentSpec): void {
  const archetype = classify(spec);
  switch (archetype) {
    case "pass-through":
      contributePassThrough(parts, spec);
      return;
    case "slotted":
      contributeSlotted(parts, spec);
      return;
    default: {
      const exhaustive: never = archetype;
      throw new Error(
        `contributeContent: unhandled archetype for "${spec.name}": ${JSON.stringify(exhaustive)}`,
      );
    }
  }
}

function contributePassThrough(parts: EmitParts, spec: SetComponentSpec): void {
  const pascal = pascalCase(spec.name);
  const buildFn = `buildSet${pascal}`;
  const corePropsType = `Set${pascal}Props`;
  const element = hostInterface(spec);

  parts.coreValueImports.add(buildFn);
  parts.coreTypeImports.add(corePropsType);
  parts.exportedTypes.push(
    `export type ${pascal}Props = ${corePropsType} & NativeAttrsFor<${element}>;`,
  );
  parts.functionSignature = `export function ${pascal}(props: ${pascal}Props): ReturnType<typeof reactify>`;
  parts.returnExpr = `reactify(\n    ${buildFn}(props),\n    pickNativeExtras(props as unknown as Record<string, unknown>),\n  )`;
}

interface SlotInfo {
  prop: string;
  kind: "text" | "html";
  required: boolean;
}

function slotsFromContent(spec: SetComponentSpec): ReadonlyArray<SlotInfo> {
  if (spec.content.kind === "html") {
    return [
      {
        prop: spec.content.prop,
        kind: "html",
        required: spec.props[spec.content.prop]?.required === true,
      },
    ];
  }
  if (spec.content.kind === "slots") {
    return spec.content.slots.map((s) => ({
      prop: s.prop,
      kind: s.kind,
      required: spec.props[s.prop]?.required === true,
    }));
  }
  throw new Error(
    `slotsFromContent: content kind "${spec.content.kind}" is not slotted for "${spec.name}"`,
  );
}

function contributeSlotted(parts: EmitParts, spec: SetComponentSpec): void {
  const slots = slotsFromContent(spec);
  const htmlSlots = slots.filter((s) => s.kind === "html");

  // All-text slots have no ReactNode substitution work — the slot values
  // are scalar strings that flow straight through to buildSet*. Route to
  // the pass-through emitter instead of generating an `Omit<X,>` with no
  // omission keys (which TS rejects).
  if (htmlSlots.length === 0) {
    contributePassThrough(parts, spec);
    return;
  }

  const pascal = pascalCase(spec.name);
  const buildFn = `buildSet${pascal}`;
  const corePropsType = `Set${pascal}Props`;
  const element = hostInterface(spec);

  parts.coreValueImports.add(buildFn);
  parts.coreTypeImports.add(corePropsType);

  parts.reactTypeImports.add("ReactNode");

  const sentinelName = (slot: SlotInfo) =>
    `SLOT_${screamingSnake(spec.name)}_${screamingSnake(slot.prop)}`;

  for (const s of htmlSlots) {
    parts.constants.push(
      `const ${sentinelName(s)} = "__SET_SLOT_${screamingSnake(spec.name)}_${screamingSnake(s.prop)}__";`,
    );
  }

  const reactNodeExtras = htmlSlots
    .map((s) => `  ${s.prop}${s.required ? "" : "?"}: ReactNode;`)
    .join("\n");
  const htmlOmitUnion = htmlSlots.map((s) => `"${s.prop}"`).join(" | ");

  parts.exportedTypes.push(
    `export type ${pascal}Props = Omit<${corePropsType}, ${htmlOmitUnion}> & {\n${reactNodeExtras}\n} & NativeAttrsFor<${element}>;`,
  );
  parts.functionSignature = `export function ${pascal}(props: ${pascal}Props): ReturnType<typeof reactify>`;

  const specPropNames = Object.keys(spec.props);
  const destructureList = [...specPropNames, "...rest"].join(", ");

  parts.destructureIndex = parts.functionBody.length;
  parts.functionBody.push(`  const { ${destructureList} } = props;`);
  for (const s of htmlSlots.filter((x) => !x.required)) {
    parts.functionBody.push(
      `  const has${pascalCase(s.prop)} = ${s.prop} != null && ${s.prop} !== false;`,
    );
  }

  const buildArgs = specPropNames
    .map((p) => {
      const slot = slots.find((s) => s.prop === p);
      if (!slot || slot.kind === "text") return `    ${p},`;
      // Cast the slot sentinel to the core prop type so branded slot
      // props (e.g. Poster's `SetPosterMedia`) accept the placeholder.
      const cast = ` as unknown as ${corePropsType}["${p}"]`;
      if (slot.required) return `    ${p}: ${sentinelName(slot)}${cast},`;
      return `    ${p}: has${pascalCase(p)} ? ${sentinelName(slot)}${cast} : undefined,`;
    })
    .join("\n");
  parts.functionBody.push(`  const node = ${buildFn}({`);
  parts.functionBody.push(buildArgs);
  parts.functionBody.push(`  });`);

  const slotsMapEntries = htmlSlots
    .map((s) =>
      s.required
        ? `    [${sentinelName(s)}]: ${s.prop},`
        : `    ...(has${pascalCase(s.prop)} ? { [${sentinelName(s)}]: ${s.prop} } : {}),`,
    )
    .join("\n");

  parts.returnExpr = `reactify(\n    node,\n    pickNativeExtras(rest as unknown as Record<string, unknown>),\n    {\n${slotsMapEntries}\n    },\n  )`;
}

// -----------------------------------------------------------------------------
// Custom-element contributor.
//
// `set-*` hosts call `defineSet<Pascal>()` from a mount-time useEffect.
// -----------------------------------------------------------------------------

function contributeCustomElement(
  parts: EmitParts,
  spec: SetComponentSpec,
): void {
  const pascal = pascalCase(spec.name);
  const defineFn = `defineSet${pascal}`;

  parts.coreValueImports.add(defineFn);
  parts.reactValueImports.add("useEffect");

  parts.functionBody.push(`  useEffect(() => {\n    ${defineFn}();\n  }, []);`);
}

// -----------------------------------------------------------------------------
// Event contributor.
//
// Each spec.events entry becomes a typed `<Pascal><Action>Handler`, an
// optional `on<Action>` prop, and a useEffect that
// addEventListener/removeEventListener via core's event-name constant.
// A callback ref merges the internal host ref with any caller-provided
// ref so both coexist.
// -----------------------------------------------------------------------------

function contributeEvents(parts: EmitParts, spec: SetComponentSpec): void {
  const pascal = pascalCase(spec.name);
  const events = Object.entries(spec.events);

  parts.reactValueImports.add("useEffect");
  parts.reactValueImports.add("useRef");
  parts.reactValueImports.add("useCallback");
  parts.reactTypeImports.add("Ref");
  parts.reactTypeImports.add("RefCallback");

  parts.helpers.push(
    [
      `function assignRef<T>(ref: Ref<T> | undefined, value: T | null): void {`,
      `  if (typeof ref === "function") ref(value);`,
      `  else if (ref) (ref as { current: T | null }).current = value;`,
      `}`,
    ].join("\n"),
  );

  const eventInfos = events.map(([eventName, eventSpec]) => {
    const action = stripSetPrefix(eventName, spec.name);
    const actionPascal = pascalCase(action);
    const handlerProp = `on${actionPascal}`;
    const baseName = `${pascal}${actionPascal}`;
    const handlerTypeName = `${baseName}Handler`;
    const detailTypeName = `${baseName}Detail`;
    const eventTypeName = `${baseName}Event`;
    const eventConstant = `SET_${screamingSnake(spec.name)}_EVENT_${screamingSnake(action)}`;
    return {
      eventName,
      action,
      actionPascal,
      handlerProp,
      handlerTypeName,
      detailTypeName,
      eventTypeName,
      eventConstant,
      detail: eventSpec.detail,
    };
  });

  // The content contributor pushed the Props type as the only entry.
  // Take it out, register handler types before it, then re-push the
  // modified Props type with handler fields injected.
  const propsType = parts.exportedTypes.shift();
  if (!propsType) throw new Error("contributeEvents: no Props type emitted");

  for (const info of eventInfos) {
    parts.coreValueImports.add(info.eventConstant);
    if (info.detail) {
      parts.exportedTypes.push(
        `export type ${info.detailTypeName} = ${info.detail};`,
      );
      parts.exportedTypes.push(
        `export type ${info.eventTypeName} = CustomEvent<${info.detailTypeName}>;`,
      );
      parts.exportedTypes.push(
        `export type ${info.handlerTypeName} = (event: ${info.eventTypeName}) => void;`,
      );
    } else {
      parts.exportedTypes.push(
        `export type ${info.handlerTypeName} = (event: Event) => void;`,
      );
    }
    parts.propsTypeLines.push(
      `  ${info.handlerProp}?: ${info.handlerTypeName};`,
    );
  }

  // Inject handler fields into the Props type via regex rewrite of what
  // the content contributor already pushed. Fragile: the pattern assumes
  // the type ends in ` & NativeAttrsFor<X>;`, optionally preceded by a
  // `}` from a slot-overlay block. If a content contributor ever emits a
  // different Props shape both patterns miss and we throw loudly — future
  // maintainers see a clear error pointing here rather than mysterious
  // "onX does not exist on Props" errors downstream. If a third concern
  // ever wants to touch Props, consider refactoring to a structured
  // Props-parts accumulator instead of adding a third regex.
  const handlerBlock = `{\n${parts.propsTypeLines.join("\n")}\n}`;
  const withSlotOverlay = propsType.replace(
    /\n\} & NativeAttrsFor<([^>]+)>;$/,
    (_, iface) => `\n} & NativeAttrsFor<${iface}> & ${handlerBlock};`,
  );
  if (withSlotOverlay !== propsType) {
    parts.exportedTypes.push(withSlotOverlay);
    return;
  }
  const passThrough = propsType.replace(
    / & NativeAttrsFor<([^>]+)>;$/,
    (_, iface) => ` & NativeAttrsFor<${iface}> & ${handlerBlock};`,
  );
  if (passThrough === propsType) {
    throw new Error(
      [
        `contributeEvents: failed to inject handler block into Props type for "${spec.name}".`,
        `  Neither the slotted pattern (ends with "} & NativeAttrsFor<X>;") nor the pass-through pattern (ends with " & NativeAttrsFor<X>;") matched.`,
        `  Got: ${propsType}`,
        `  Most likely a content contributor now emits a different Props shape. Fix either the contributor or refactor contributeEvents — see the comment above this throw.`,
      ].join("\n"),
    );
  }
  parts.exportedTypes.push(passThrough);

  // Destructure event handlers + caller ref from props. Two paths,
  // dispatched via `parts.destructureIndex`:
  //   - Content contributor set it (slotted case): extend that line in
  //     place, preserving surrounding lines (e.g. `useEffect(defineSet*)`
  //     from the CE contributor may sit before or after it).
  //   - Not set (pass-through case): insert a fresh destructure at the top
  //     that introduces `rest`.
  // If the recorded index now points at something that isn't a destructure
  // line, a content contributor has changed its output format — throw.
  const handlerDestructures = eventInfos.map((i) => i.handlerProp);
  let destructuredRest = false;
  if (parts.destructureIndex === null) {
    parts.functionBody.unshift(
      `  const { ${handlerDestructures.join(", ")}, ref: callerRef, ...rest } = props;`,
    );
    destructuredRest = true;
  } else {
    const existing = parts.functionBody[parts.destructureIndex] ?? "";
    if (!existing.startsWith("  const {") || !existing.endsWith("= props;")) {
      throw new Error(
        [
          `contributeEvents: functionBody[${parts.destructureIndex}] was expected to be the "const { … } = props;" destructure recorded by a content contributor for "${spec.name}", but got:`,
          `  ${existing}`,
          `  A content contributor has changed its output format. Update the contributor (or refactor to a structured functionBody accumulator).`,
        ].join("\n"),
      );
    }
    parts.functionBody[parts.destructureIndex] = existing.replace(
      /const \{ /,
      `const { ${handlerDestructures.join(", ")}, ref: callerRef, `,
    );
  }

  parts.functionBody.push(`  const elRef = useRef<HTMLElement | null>(null);`);

  for (const info of eventInfos) {
    parts.functionBody.push(
      [
        `  useEffect(() => {`,
        `    const el = elRef.current;`,
        `    if (!el || !${info.handlerProp}) return;`,
        `    el.addEventListener(${info.eventConstant}, ${info.handlerProp} as EventListener);`,
        `    return () =>`,
        `      el.removeEventListener(${info.eventConstant}, ${info.handlerProp} as EventListener);`,
        `  }, [${info.handlerProp}]);`,
      ].join("\n"),
    );
  }

  parts.functionBody.push(
    [
      `  const mergedRef = useCallback<RefCallback<HTMLElement>>(`,
      `    (node) => {`,
      `      elRef.current = node;`,
      `      assignRef(callerRef, node);`,
      `    },`,
      `    [callerRef],`,
      `  );`,
    ].join("\n"),
  );

  // Rewrite the return to thread `mergedRef` through pickNativeExtras. The
  // content contributors produced either a pass-through return (uses
  // `props`) or a slotted return (uses `rest`). If events forced a rest
  // destructure into the body, redirect pickNativeExtras to the new `rest`
  // so event handlers don't leak onto the host via `on*` pass-through. If
  // the regex stops matching (content contributor changed returnExpr
  // shape), throw — otherwise mergedRef silently never threads and events
  // fail at runtime with no compile error.
  const existing = parts.returnExpr;
  const source = destructuredRest ? "rest" : "$1";
  const threaded = existing.replace(
    /pickNativeExtras\((props|rest) as unknown as Record<string, unknown>\)/,
    `{\n    ...pickNativeExtras(${source} as unknown as Record<string, unknown>),\n    ref: mergedRef,\n  }`,
  );
  if (threaded === existing) {
    throw new Error(
      [
        `contributeEvents: returnExpr for "${spec.name}" didn't contain the expected \`pickNativeExtras(props|rest as unknown as Record<string, unknown>)\` call.`,
        `  Got: ${existing}`,
        `  A content contributor has changed its returnExpr shape. Update this regex (or refactor to a structured returnExpr accumulator) — without this rewrite mergedRef never threads and custom events silently fail to wire at runtime.`,
      ].join("\n"),
    );
  }
  parts.returnExpr = threaded;
}

function stripSetPrefix(eventName: string, componentName: string): string {
  const prefix = `set-${componentName}-`;
  if (!eventName.startsWith(prefix)) {
    throw new Error(
      `stripSetPrefix: "${eventName}" doesn't start with "${prefix}"`,
    );
  }
  return eventName.slice(prefix.length);
}
