// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetGridItem, type SetGridItemProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_GRID_ITEM_CHILDREN = "__SET_SLOT_GRID_ITEM_CHILDREN__";

export type GridItemProps = Omit<SetGridItemProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function GridItem(props: GridItemProps): ReturnType<typeof reactify> {
  const {
    children,
    align,
    justify,
    colSpan,
    colStart,
    id,
    rowSpan,
    rowSpanNarrow,
    rowSpanWide,
    rowStart,
    rowStartNarrow,
    rowStartWide,
    colSpanNarrow,
    colStartNarrow,
    colSpanWide,
    colStartWide,
    ...rest
  } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetGridItem({
    children: hasChildren
      ? (SLOT_GRID_ITEM_CHILDREN as unknown as SetGridItemProps["children"])
      : undefined,
    align,
    justify,
    colSpan,
    colStart,
    id,
    rowSpan,
    rowSpanNarrow,
    rowSpanWide,
    rowStart,
    rowStartNarrow,
    rowStartWide,
    colSpanNarrow,
    colStartNarrow,
    colSpanWide,
    colStartWide,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_GRID_ITEM_CHILDREN]: children } : {}),
    },
  );
}
