// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetBanner,
  SET_BANNER_EVENT_BEFORE_DISMISS,
  SET_BANNER_EVENT_DISMISS,
  type SetBannerProps,
  defineSetBanner,
} from "@measured/set-core";
import {
  type Ref,
  type RefCallback,
  useCallback,
  useEffect,
  useRef,
} from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

function assignRef<T>(ref: Ref<T> | undefined, value: T | null): void {
  if (typeof ref === "function") ref(value);
  else if (ref) (ref as { current: T | null }).current = value;
}

export type BannerBeforeDismissHandler = (event: Event) => void;

export type BannerDismissHandler = (event: Event) => void;

export type BannerProps = SetBannerProps &
  NativeAttrsFor<HTMLElement> & {
    onBeforeDismiss?: BannerBeforeDismissHandler;
    onDismiss?: BannerDismissHandler;
  };

export function Banner(props: BannerProps): ReturnType<typeof reactify> {
  const { onBeforeDismiss, onDismiss, ref: callerRef, ...rest } = props;
  useEffect(() => {
    defineSetBanner();
  }, []);
  const elRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    const el = elRef.current;
    if (!el || !onBeforeDismiss) return;
    el.addEventListener(
      SET_BANNER_EVENT_BEFORE_DISMISS,
      onBeforeDismiss as EventListener,
    );
    return () =>
      el.removeEventListener(
        SET_BANNER_EVENT_BEFORE_DISMISS,
        onBeforeDismiss as EventListener,
      );
  }, [onBeforeDismiss]);
  useEffect(() => {
    const el = elRef.current;
    if (!el || !onDismiss) return;
    el.addEventListener(SET_BANNER_EVENT_DISMISS, onDismiss as EventListener);
    return () =>
      el.removeEventListener(
        SET_BANNER_EVENT_DISMISS,
        onDismiss as EventListener,
      );
  }, [onDismiss]);
  const mergedRef = useCallback<RefCallback<HTMLElement>>(
    (node) => {
      elRef.current = node;
      assignRef(callerRef, node);
    },
    [callerRef],
  );
  return reactify(buildSetBanner(props), {
    ...pickNativeExtras(rest as unknown as Record<string, unknown>),
    ref: mergedRef,
  });
}
