// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetText, type SetTextProps } from "@monospaced/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_TEXT_CHILDREN = "__SET_SLOT_TEXT_CHILDREN__";

export type TextProps = Omit<SetTextProps, "children"> & {
  children: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Text(props: TextProps): ReturnType<typeof reactify> {
  const {
    as,
    children,
    id,
    linkVisited,
    responsive,
    align,
    measured,
    monospaced,
    size,
    tone,
    ...rest
  } = props;
  const node = buildSetText({
    as,
    children: SLOT_TEXT_CHILDREN as unknown as SetTextProps["children"],
    id,
    linkVisited,
    responsive,
    align,
    measured,
    monospaced,
    size,
    tone,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_TEXT_CHILDREN]: children,
    },
  );
}
