// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetBadge, type SetBadgeProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type BadgeProps = SetBadgeProps & NativeAttrsFor<HTMLSpanElement>;

export function Badge(props: BadgeProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetBadge(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
