// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetIcon, type SetIconProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type IconProps = SetIconProps & NativeAttrsFor<SVGSVGElement>;

export function Icon(props: IconProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetIcon(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
