// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetExpander, type SetExpanderProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type ExpanderProps = SetExpanderProps &
  NativeAttrsFor<HTMLButtonElement>;

export function Expander(props: ExpanderProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetExpander(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
