// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetTextarea, type SetTextareaProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type TextareaProps = SetTextareaProps & NativeAttrsFor<HTMLDivElement>;

export function Textarea(props: TextareaProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetTextarea(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
