// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetBox, type SetBoxProps } from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_BOX_CHILDREN = "__SET_SLOT_BOX_CHILDREN__";

export type BoxProps = Omit<SetBoxProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Box(props: BoxProps): ReturnType<typeof reactify> {
  const {
    background,
    border,
    children,
    id,
    paddingBlock,
    paddingInline,
    radius,
    responsive,
    surface,
    ...rest
  } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetBox({
    background,
    border,
    children: hasChildren
      ? (SLOT_BOX_CHILDREN as unknown as SetBoxProps["children"])
      : undefined,
    id,
    paddingBlock,
    paddingInline,
    radius,
    responsive,
    surface,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_BOX_CHILDREN]: children } : {}),
    },
  );
}
