// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetRange,
  defineSetRange,
  type SetRangeProps,
} from "@monospaced/set-core";
import { useEffect } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type RangeProps = SetRangeProps & NativeAttrsFor<HTMLElement>;

export function Range(props: RangeProps): ReturnType<typeof reactify> {
  useEffect(() => {
    defineSetRange();
  }, []);
  return reactify(
    buildSetRange(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
