// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetBlockquote,
  type SetBlockquoteProps,
} from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_BLOCKQUOTE_QUOTE = "__SET_SLOT_BLOCKQUOTE_QUOTE__";
const SLOT_BLOCKQUOTE_ATTRIBUTION = "__SET_SLOT_BLOCKQUOTE_ATTRIBUTION__";

export type BlockquoteProps = Omit<
  SetBlockquoteProps,
  "quote" | "attribution"
> & {
  quote: ReactNode;
  attribution: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Blockquote(
  props: BlockquoteProps,
): ReturnType<typeof reactify> {
  const { align, attribution, id, measured, quote, responsive, size, ...rest } =
    props;
  const node = buildSetBlockquote({
    align,
    attribution:
      SLOT_BLOCKQUOTE_ATTRIBUTION as unknown as SetBlockquoteProps["attribution"],
    id,
    measured,
    quote: SLOT_BLOCKQUOTE_QUOTE as unknown as SetBlockquoteProps["quote"],
    responsive,
    size,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      [SLOT_BLOCKQUOTE_QUOTE]: quote,
      [SLOT_BLOCKQUOTE_ATTRIBUTION]: attribution,
    },
  );
}
