// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetVideo,
  defineSetVideo,
  type SetVideoProps,
} from "@monospaced/set-core";
import { useEffect } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type VideoProps = SetVideoProps & NativeAttrsFor<HTMLElement>;

export function Video(props: VideoProps): ReturnType<typeof reactify> {
  useEffect(() => {
    defineSetVideo();
  }, []);
  return reactify(
    buildSetVideo(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
