// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetVideo, type SetVideoProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type VideoProps = SetVideoProps & NativeAttrsFor<HTMLDivElement>;

export function Video(props: VideoProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetVideo(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
