// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetButton, type SetButtonProps } from "@monospaced/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type ButtonProps = SetButtonProps & NativeAttrsFor<HTMLButtonElement>;

export function Button(props: ButtonProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetButton(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
