// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetPattern, type SetPatternProps } from "@measured/set-core";
import type { ReactNode } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_PATTERN_CHILDREN = "__SET_SLOT_PATTERN_CHILDREN__";

export type PatternProps = Omit<SetPatternProps, "children"> & {
  children?: ReactNode;
} & NativeAttrsFor<HTMLDivElement>;

export function Pattern(props: PatternProps): ReturnType<typeof reactify> {
  const { children, id, tone, size, variant, ...rest } = props;
  const hasChildren = children != null && children !== false;
  const node = buildSetPattern({
    children: hasChildren
      ? (SLOT_PATTERN_CHILDREN as unknown as SetPatternProps["children"])
      : undefined,
    id,
    tone,
    size,
    variant,
  });
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasChildren ? { [SLOT_PATTERN_CHILDREN]: children } : {}),
    },
  );
}
