// Generated by @measured/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import { buildSetImage, type SetImageProps } from "@measured/set-core";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type ImageProps = SetImageProps & NativeAttrsFor<HTMLDivElement>;

export function Image(props: ImageProps): ReturnType<typeof reactify> {
  return reactify(
    buildSetImage(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
