// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetImage,
  defineSetImage,
  type SetImageProps,
} from "@monospaced/set-core";
import { useEffect } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

export type ImageProps = SetImageProps & NativeAttrsFor<HTMLElement>;

export function Image(props: ImageProps): ReturnType<typeof reactify> {
  useEffect(() => {
    defineSetImage();
  }, []);
  return reactify(
    buildSetImage(props),
    pickNativeExtras(props as unknown as Record<string, unknown>),
  );
}
