// Generated by @monospaced/set-adapter — do not edit directly.
// Regenerate with `pnpm react:generate` (runs automatically on `pnpm react:build`).
import {
  buildSetSidebar,
  defineSetSidebar,
  type SetSidebarProps,
} from "@monospaced/set-core";
import { type ReactNode, useEffect } from "react";

import {
  type NativeAttrsFor,
  pickNativeExtras,
  reactify,
} from "../../reactify";

const SLOT_SIDEBAR_HEADER = "__SET_SLOT_SIDEBAR_HEADER__";
const SLOT_SIDEBAR_CHILDREN = "__SET_SLOT_SIDEBAR_CHILDREN__";
const SLOT_SIDEBAR_FOOTER = "__SET_SLOT_SIDEBAR_FOOTER__";

export type SidebarProps = Omit<
  SetSidebarProps,
  "header" | "children" | "footer"
> & {
  header?: ReactNode;
  children?: ReactNode;
  footer?: ReactNode;
} & NativeAttrsFor<HTMLElement>;

export function Sidebar(props: SidebarProps): ReturnType<typeof reactify> {
  const {
    aboveNotebook,
    buttonSize,
    children,
    collapseLabel,
    footer,
    header,
    id,
    surface,
    triggerLabel,
    ...rest
  } = props;
  const hasHeader = header != null && header !== false;
  const hasChildren = children != null && children !== false;
  const hasFooter = footer != null && footer !== false;
  const node = buildSetSidebar({
    aboveNotebook,
    buttonSize,
    children: hasChildren
      ? (SLOT_SIDEBAR_CHILDREN as unknown as SetSidebarProps["children"])
      : undefined,
    collapseLabel,
    footer: hasFooter
      ? (SLOT_SIDEBAR_FOOTER as unknown as SetSidebarProps["footer"])
      : undefined,
    header: hasHeader
      ? (SLOT_SIDEBAR_HEADER as unknown as SetSidebarProps["header"])
      : undefined,
    id,
    surface,
    triggerLabel,
  });
  useEffect(() => {
    defineSetSidebar();
  }, []);
  return reactify(
    node,
    pickNativeExtras(rest as unknown as Record<string, unknown>),
    {
      ...(hasHeader ? { [SLOT_SIDEBAR_HEADER]: header } : {}),
      ...(hasChildren ? { [SLOT_SIDEBAR_CHILDREN]: children } : {}),
      ...(hasFooter ? { [SLOT_SIDEBAR_FOOTER]: footer } : {}),
    },
  );
}
